In [ ]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [5]:
df.sample(5)

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
41149,49,technician,single,secondary,no,9131,yes,no,cellular,18,aug,532,1,461,5,failure,yes
34658,30,management,married,tertiary,no,6432,yes,no,cellular,5,may,334,6,165,5,failure,no
27337,48,housemaid,single,secondary,no,1385,no,no,telephone,21,nov,270,1,-1,0,unknown,no
24036,59,blue-collar,married,primary,no,1227,no,no,cellular,29,aug,89,5,-1,0,unknown,no
14193,31,technician,single,tertiary,no,696,no,yes,cellular,11,jul,184,2,-1,0,unknown,no

In [11]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numeric columns:", numeric_cols)
nominal_cols = df.select_dtypes(include=['object']).columns
print("Nominal columns:", nominal_cols)
ordinal_cols1 = df['TARGET']
print("Ordinal columns:", ordinal_cols1)

Numeric columns: Index(['Age', 'Balance', 'Day', 'Duration', 'Campaign', 'Pdays', 'Previous'], dtype='object')
Nominal columns: Index(['Job', 'Marital', 'Education', 'Default', 'Housing', 'Loan', 'contact',
       'Month', 'poutcome', 'TARGET'],
      dtype='object')
Ordinal columns: 0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: object

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder

In [14]:
x = df[::-1]
y = df["TARGET"]

In [15]:
y = le.fit_transform

In [3]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
from pandas.core.common import random_state
data = load_iris()
X = data.data
y = data.target 
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegressionCV
lr = LogisticRegressionCV(cv=5)
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)